version: '2'

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./front-end/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/app/api/django_static
            - ./nginx/:/etc/nginx/conf.d
            - media_volume:/media/app_media/
        depends_on: 
            - backend

    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./api/Dockerfile
            
        entrypoint: /app/api/entrypoint.sh
        volumes:
            - static_volume:/app/backend/server/django_static
            - media_volume:/media/app_media/
        expose:
            - 8000
          
        depends_on:
          - db
      
    db:
      restart: unless-stopped
      image: postgres:10-alpine
      expose:
        - 5432

      environment:
        - POSTGRES_PASSWORD=cowabanga
        - POSTGRES_USER=postgres
        - APP_DB_NAME=birthday
        - APP_DB_USER=birthday
        - APP_DB_PASS=simpletone

      volumes:
        - ./db:/docker-entrypoint-initdb.d/
        - db_volume:/var/lib/postgresql/data

volumes:
    db_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/shafi/docker-volumes/docker_talk/db/'
    
    media_volume:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/shafi/docker-volumes/docker_talk/media/'

    static_volume: {}
