# Generated by Django 3.1.4 on 2021-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('data_of_birth', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
