# Generated by Django 3.1.4 on 2021-08-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
